export const categoryData = [
    {
        id: "01",
        name: "Fashion Photography",
        image: "/images/fashion.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "02",
        name: "Wedding Photography",
        image: "/images/wedding.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "03",
        name: "Landscape Photography",
        image: "/images/landscape.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "04",
        name: "Candid Photography",
        image: "/images/candid.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "05",
        name: "Fashion Photography",
        image: "/images/fashion.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "06",
        name: "Wedding Photography",
        image: "/images/wedding.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "07",
        name: "Landscape Photography",
        image: "/images/landscape.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
    {
        id: "08",
        name: "Candid Photography",
        image: "/images/candid.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },

    {
        id: "09",
        name: "Wedding Photography",
        image: "/images/wedding.png",
        imageAlt: "Fashion",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae vero, id quae nihil iusto, odio porro suscipit consequatur hic similique ex provident corporis incidunt magni quidem.",
    },
]